### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by dmiedev** [anharu2394/tapioca#35]
Hello @anharu2394 @tokku5552 

Are there any plans to migrate to null safety?

**Comment by KyleKun** [comment]
Hey, I needed the same and did the migration on my fork, just set this on your pubspec:

```
tapioca:
    git:
      url: https://github.com/KyleKun/tapioca.git
      ref: master
```
